apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "smart-proxy.fullname" . }}
  labels:
    {{- include "smart-proxy.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "smart-proxy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "smart-proxy.selectorLabels" . | nindent 8 }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ include "smart-proxy.serviceAccountName" . }}
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: proxy
              containerPort: {{ .Values.config.proxyPort }}
            - name: admin
              containerPort: {{ .Values.config.adminPort }}
          env:
            - name: WATCH_NAMESPACE
            {{- if .Values.config.watchNamespace }}
              value: {{ .Values.config.watchNamespace | quote }}
            {{- else }}
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            {{- end }}
            - name: SMART_PROXY_PORT
              value: {{ .Values.config.proxyPort | quote }}
            - name: LOG_LEVEL
              value: {{ .Values.config.logLevel | quote }}
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
        {{- if .Values.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ include "smart-proxy.fullname" . }}-data
        {{- else }}
          emptyDir: {}
        {{- end }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
